### ISSUE TITLE
Add mod to Curseforge

### ISSUE THREAD

**Issue by tlm9201** [HttpRafa/Modflared#27]
**Problem:** I make modpacks and host servers with Cloudflared/Modflared. Whenever I make a modpack on curseforge I have to manually add the Modflared to the mods folder. I can't export the modpack directly on curseforge because it doesn't recognize modflared. Instead, players have to manually download a zip file and upload it to curseforge themselves.

**Solution:** Upload the mod (all versions) to Curseforge.

**Comment by HttpRafa** [comment]
I will upload the mod to Curseforge.

**Comment by HttpRafa** [comment]
Which Minecraft version do you need?

**Comment by tlm9201** [comment]
1.18.2 & 1.20.4

**Comment by tlm9201** [comment]
> Which Minecraft version do you need?

1.20.1 as well

**Comment by HttpRafa** [comment]
I have backported the mod for versions 1.20.1 and 1.18.2. It is possible that these versions contain errors because I have not yet been able to test them properly. If you find any errors, feel free to create an issue. 1.20.4 should be the same as on Modrinth. Hopefully the project on [Curseforge](https://legacy.curseforge.com/minecraft/mc-mods/modflared) will be approved by tomorrow.
