### ISSUE TITLE
Is it possible to make the mod also server-side?

### ISSUE THREAD

**Issue by crazypotato142** [HttpRafa/Modflared#34]
The mod is great, I just placed it to my modpack so my friends can join me freely without installing anything else. 

But I was wondering that is it possible to make the mod also server-side? Like, instead of setting up Cloudflared on the server, just place Modflared to the mods folder on Minecraft server. So it just would be able to run only when the Minecraft server is running, and Cloudflared shuts down when the Minecraft server is closed as well. Or is there any existing way to do this?

I'm asking because I created my server on my own PC, not on a different computer else than I play the game. I'm playing on 1.20.1

**Comment by HttpRafa** [comment]
I'll probably get around to it at some point, but unfortunately I don't have much time at the moment.

**Comment by HttpRafa** [comment]
The problem is that Cloudflared was designed to run constantly in the background. If you follow the setup, it installs it globally as a service and the config file is also installed in a global folder. In my opinion, having the server start the Cloudflared binary would only make the installation extremely difficult. Because the step-by-step installation on the Cloudflare panel doesn't work this way.

**Comment by HttpRafa** [comment]
If you are using Linux you can disable the service so that it does not start automatically with `sudo systemctl disable cloudflared.service` and add `sudo service cloudflared start` and `sudo service cloudflared stop` to your start.sh. If you are using Windows I am not entirely sure how to do it.

**Comment by HttpRafa** [comment]
If you are using Linux you can disable the service so that it does not start automatically with `sudo systemctl disable cloudflared.service` and add `sudo service cloudflared start` and `sudo service cloudflared stop` to your start.sh. If you are using Windows you can do:
1. Search for "`service`" in the taskbar, open the Services app, find `cloudflared`, change the start type to manual.
2. Add `net start [serviceName] /y` and `net stop [serviceName] /y` to your start.bat

[Start-Stop Windows](https://stackoverflow.com/questions/133883/stop-and-start-a-service-via-batch-or-cmd-file)
[Stop it from starting on boot](https://www.reddit.com/r/CloudFlare/comments/138wj2g/how_i_can_stop_cloudflare_from_starting_automatic/)

**Comment by crazypotato142** [comment]
sorry for late reply, didnt have any notifications.

seems fair, i think i ll use the start-stop BAT file. thank you for considering it!
